version: "3.8"

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3005:3000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    volumes:
      - ./client/src:/app/src
